######## IOS CONFIGURATIONS
# If you want to make the build automatically available to external groups,
# add the name of the group to the array below, after "App Store Connect Users"
groups = ["External Tests group name"]
workspace = "Event.xcworkspace"
project = "Event.xcodeproj"
slack_weebhook_url = ENV["SLACK_WEBHOOK_URL"]
# If you build for multiple environments, you might wanna set this specifically on build_app
configuration = "Release"
scheme = "Event"
export_method = "app-store" 
key_id = "58G49UC4M4" 
issuer_id = "148294b2-7612-46d9-9e06-477538a3f357" 
key_filepath = "/Users/htetaungshine/iospj/Event/fastlane/AuthKey_58G49UC4M4.p8" 
######## END IOS CONFIGURATIONS


default_platform(:ios)
platform :ios do
  desc "Push a new build to TestFlight"
  lane :release do
    setup_ci
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_filepath,
      in_house: true
    )
    latest_build_number = latest_testflight_build_number(
        api_key: api_key,
        app_identifier: app_identifier
    )
    increment_build_number(
        build_number: (latest_build_number + 1),
    )

    clear_derived_data
    match(api_key: api_key)
    
    gym(
      scheme: scheme,
      configuration: configuration,
      export_options: {
        method: export_method,
        compile_bitcode: true
      }
    )
    pilot(
      changelog: "Build #{latest_build_number + 1}",
      api_key: api_key,
      app_identifier: app_identifier,
      distribute_external: true,
      groups: groups,
    )
    clean_build_artifacts
  end
end