name: ios-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      P8_AUTH_KEY: ${{ secrets.P8_AUTH_KEY }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ITUNES_TEAM_ID: ${{ secrets.ITUNES_TEAM_ID }}
      APPSTORE_TEAM_ID: ${{ secrets.APPSTORE_TEAM_ID }}
      MATCH_REPO_SSH: ${{ secrets.MATCH_REPO_SSH }}
      BASE_URL: ${{ vars.BASE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      
      - name: Setup SSH for Match repo
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MATCH_REPO_KEY }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
      
      - name: Install Bundler
        run: gem install bundler --no-document
      
      - name: Install Ruby dependencies
        run: |
          cd ios # only if Gemfile is inside ios/
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods & JS dependencies
        run: |
          npm install
          cd ios
          pod install --repo-update

      - name: Build and deploy via Fastlane
        run: |
          cd ios
          echo "${{ secrets.P8_AUTH_KEY }}" > secretKey.p8
          bundle exec fastlane ios release
